@a = a71663b0-9d93-474b-8551-7bdc7f93f036
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OWU1NTQ2OC1hNjk1LTRiNDYtYjRhMS03OTNkM2MwYzBjYTciLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJmYW1pbHlfbmFtZSI6IlN5c3RlbSIsIm1pZGRsZV9uYW1lIjoiIiwianRpIjoiOGJiNjgxZWUtMWY5Zi00ZGJlLTkxODktZTM1ZWUwNjRkNTQ1IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjYwNzkyNDcsImV4cCI6MTc2NjA4Mjg0NywiaXNzIjoiTWljcm9TZXJ2aWNlVXNlcnMiLCJhdWQiOiJCb29rc3RvcmVDbGllbnRzIn0.ZSOkxToT1A8TPD0gVfFiHsi_VNuLalyPIhQJDjmtBnw
GET http://localhost:50360/api/user?id={{a}}
Authorization: Bearer {{token}}