name: Pipeline, Coverage of Unit Tests .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar entorno .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: 3. Restaurar dependencias (NuGet)
      run: dotnet restore

    - name: 4. Compilar la solución
      run: dotnet build --no-restore

    - name: 5. Ejecutar Pruebas Unitarias con Cobertura
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: 6. Generar informe detallado de cobertura
      run: pwsh -File ./Scripts/global-coverage.ps1

    - name: 7. Verificar salida del reporte
      run: ls -la ./GlobalCoverageReport

    - name: 8. Publicar informe de cobertura como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: global-coverage-report
        path: ./GlobalCoverageReport/
        if-no-files-found: error